services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      SERVER_CONNECTIONS_POOL_SIZE: "10"
      NEWS_SUMMARY_REPORT_PERIOD_IN_SECONDS: "10"

  client:
    build:
      context: .
      dockerfile: mock-news-feed-client/Dockerfile
    environment:
      NEWS_ANALYZE_SERVER_HOST: "server"
      NEWS_ANALYZE_SERVER_PORT: "8080"
      SEND_MESSAGE_INTERVAL_IN_MS: "200"
    depends_on:
      - server

networks:
  default:
    name: news-network
    driver: bridge